version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: bitespeed_postgres
    environment:
      POSTGRES_USER: postgres        
      POSTGRES_PASSWORD: 12345 
      POSTGRES_DB: bitespeed_task_db  
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitespeed_app
    ports:
      - "3000:3000" 
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres 
      DB_PORT: 5432
      DB_USER: postgres 
      DB_PASSWORD: 12345
      DB_NAME: bitespeed_task_db 
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
    command: npm run dev 

volumes:
  postgres_data: 