version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: bitespeed_postgres
    environment:
      POSTGRES_USER: your_db_user       # Replace with your .env DB_USER
      POSTGRES_PASSWORD: your_db_password # Replace with your .env DB_PASSWORD
      POSTGRES_DB: bitespeed_identity_db # Replace with your .env DB_NAME
    ports:
      - "5432:5432" # Maps container port 5432 to host port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitespeed_app
    ports:
      - "3000:3000" # Maps container port 3000 to host port 3000
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres # Service name from docker-compose
      DB_PORT: 5432
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      DB_NAME: bitespeed_identity_db
    volumes:
      - .:/usr/src/app # Mounts current directory to /usr/src/app in container
      - /usr/src/app/node_modules # Excludes node_modules from being overwritten by host
    command: npm run dev # Or npm run start for production build

volumes:
  postgres_data: # Persists PostgreSQL data